version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Asia/Kolkata
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: concurrently
    versions:
    - 6.0.1
