# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Client CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-client:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --prefix client
    - run: npm run build --prefix client
    - run: npm run export --prefix client
#     - uses: actions/cache@v2
#       id: restore-build
#       with:
#         path: ./*
#         key: ${{ github.sha }}
    - uses: actions/upload-artifact@v2
      with:
        name: nextjs-build
        path: ./out
  
  Deploy 🚀:
    name: Re-use Artifact
    runs-on: ubuntu-latest
    needs: [build-client]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/download-artifact@v2
        with:
          name: nextjs-build
      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
      
      
      
      
      
      
      
      
      
      
      
      
      
